# Generated by Django 2.0.5 on 2018-10-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
