# Generated by Django 2.0.5 on 2018-10-20 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('date_published', models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Date First Available')),
                ('description', models.TextField(max_length=300)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('quantities_available', models.IntegerField(blank=True, null=True, verbose_name='Availabe Quantities')),
                ('quantity_weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cloths', 'Cloths'), ('show piece', 'Show Piece'), ('home appliance', 'Home Appliance'), ('solar product', 'Solar Product'), ('accessories', 'Accessories')], max_length=20)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='')),
                ('date_first_available', models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Date First Available')),
                ('description', models.TextField(max_length=300)),
                ('quantities_available', models.IntegerField(verbose_name='Availabe Quantities')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellersapp.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review_title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Product')),
            ],
        ),
    ]
