# Generated by Django 2.0.5 on 2018-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_first_available',
            field=models.DateField(auto_now=True, max_length=50, verbose_name='Date First Available'),
        ),
    ]
