# Generated by Django 2.0.5 on 2018-10-20 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20181020_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_first_available',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Date First Available'),
        ),
    ]
