# Generated by Django 2.0.5 on 2018-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20181020_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_first_available',
            field=models.CharField(default='20/10/2018', max_length=500, verbose_name='Date First Available'),
        ),
    ]
